#!/bin/bash

# Dotfiles Restore Script
# Im gonna keep it a buck this is generated by claude it might fuck your shit up
# This script restores all backed up configuration files to their original locations

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}Restoring dotfiles...${NC}\n"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Vim
if [ -f "$SCRIPT_DIR/vim/vimrc" ]; then
    echo -e "${YELLOW}Restoring vim configuration...${NC}"
    cp "$SCRIPT_DIR/vim/vimrc" ~/.vimrc
    echo -e "${GREEN}* Restored ~/.vimrc${NC}"
fi

if [ -f "$SCRIPT_DIR/vim/autoload/plug.vim" ]; then
    mkdir -p ~/.vim/autoload
    cp "$SCRIPT_DIR/vim/autoload/plug.vim" ~/.vim/autoload/plug.vim
    echo -e "${GREEN}* Restored vim-plug${NC}"
fi

# Kitty
if [ -f "$SCRIPT_DIR/kitty/kitty.conf" ]; then
    echo -e "${YELLOW}Restoring kitty configuration...${NC}"
    mkdir -p ~/.config/kitty
    cp "$SCRIPT_DIR/kitty/kitty.conf" ~/.config/kitty/kitty.conf
    echo -e "${GREEN}* Restored ~/.config/kitty/kitty.conf${NC}"
fi

# Fish
if [ -f "$SCRIPT_DIR/fish/config.fish" ]; then
    echo -e "${YELLOW}Restoring fish configuration...${NC}"
    mkdir -p ~/.config/fish/functions
    cp "$SCRIPT_DIR/fish/config.fish" ~/.config/fish/config.fish
    echo -e "${GREEN}* Restored ~/.config/fish/config.fish${NC}"
fi

if [ -f "$SCRIPT_DIR/fish/fish_variables" ]; then
    cp "$SCRIPT_DIR/fish/fish_variables" ~/.config/fish/fish_variables
    echo -e "${GREEN}* Restored fish variables${NC}"
fi

if [ -f "$SCRIPT_DIR/fish/functions/fish_prompt.fish" ]; then
    cp "$SCRIPT_DIR/fish/functions/fish_prompt.fish" ~/.config/fish/functions/fish_prompt.fish
    echo -e "${GREEN}* Restored fish prompt${NC}"
fi

if [ -d "$SCRIPT_DIR/fish/functions" ]; then
    cp -r "$SCRIPT_DIR/fish/functions"/* ~/.config/fish/functions/ 2>/dev/null || true
    echo -e "${GREEN}* Restored fish functions${NC}"
fi

# Tmux
if [ -f "$SCRIPT_DIR/tmux/tmux.conf" ]; then
    echo -e "${YELLOW}Restoring tmux configuration...${NC}"
    cp "$SCRIPT_DIR/tmux/tmux.conf" ~/.tmux.conf
    echo -e "${GREEN}* Restored ~/.tmux.conf${NC}"
fi

# Git
if [ -f "$SCRIPT_DIR/git/gitconfig" ]; then
    echo -e "${YELLOW}Restoring git configuration...${NC}"
    cp "$SCRIPT_DIR/git/gitconfig" ~/.gitconfig
    echo -e "${GREEN}* Restored ~/.gitconfig${NC}"
fi

# Bash
if [ -f "$SCRIPT_DIR/bashrc" ]; then
    echo -e "${YELLOW}Restoring bash configuration...${NC}"
    cp "$SCRIPT_DIR/bashrc" ~/.bashrc
    echo -e "${GREEN}* Restored ~/.bashrc${NC}"
fi

if [ -f "$SCRIPT_DIR/bash_profile" ]; then
    cp "$SCRIPT_DIR/bash_profile" ~/.bash_profile
    echo -e "${GREEN}* Restored ~/.bash_profile${NC}"
fi

# Zsh
if [ -f "$SCRIPT_DIR/zshrc" ]; then
    echo -e "${YELLOW}Restoring zsh configuration...${NC}"
    cp "$SCRIPT_DIR/zshrc" ~/.zshrc
    echo -e "${GREEN}* Restored ~/.zshrc${NC}"
fi

echo -e "\n${GREEN}Dotfiles restored successfully!${NC}"
echo -e "${YELLOW}Note: You may need to:${NC}"
echo -e "  1. Restart your terminal"
echo -e "  2. Run 'vim +PlugInstall +qall' to install vim plugins"
echo -e "  3. Install fish plugins if using Fisher"
